version: '2.1'
services:
  amule:
    container_name: amule
    image: minnyres/amule-dlp:latest
    restart: unless-stopped
    network_mode: bridge
    ports:
      - "4711:4711"
      - "4712:4712"
      - "24662:24662"
      - "24665:24665/udp"
      - "24672:24672/udp"
    environment:
      - UID=1000
      - GID=1000
      - WEBUI=bootstrap
      - ECPASSWD=amule-passwd
      - WEBPASSWD=amuleweb-passwd
      - TIMEZONE=Asia/Shanghai
      - RECURSIVE_SHARE=yes
    volumes:
      - <config>:/config
      - <downloads>:/downloads
      - <temp>:/temp