version: '2.1'
services:
  amule:
    container_name: amule
    image: minnyres/amule-dlp
    restart: unless-stopped
    network_mode: host
    environment:
      - UID=1000
      - GID=1000
      - WEBUI=bootstrap
      - ECPASSWD=amule-passwd
      - TIMEZONE=Asia/Shanghai
      - RECURSIVE_SHARE=yes
    volumes:
      - <config>:/config
      - <downloads>:/downloads
      - <temp>:/temp