name: Docker Image CI

on:
  workflow_dispatch:
    
jobs:
  build:
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm/v6, linux/arm/v7, linux/arm64/v8, linux/ppc64le, linux/s390x, linux/riscv64]

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v2
    
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: setValues
      id: setValues
      run: |
        arch=${{ matrix.platform }}
        arch=${arch#*/}
        arch=$(echo $arch | sed 's/\//-/g')
        echo "CPU_ARCH=${arch}" >> $GITHUB_OUTPUT
          
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1.0.1
          
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
          context: ./
          file: ./Dockerfile
          push: true
          platforms: ${{ matrix.platform }}
          tags: minnyres/amule-dlp:${{ steps.setValues.outputs.CPU_ARCH }}
