name: Docker Image CI

on:
  workflow_dispatch:
    
jobs:

  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    
    - uses: actions/checkout@v2
    
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1.0.1
          
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
          context: ./
          file: ./official-2.3.3/Dockerfile
          push: true
          platforms: linux/arm,linux/arm64,linux/amd64
          tags: minnyres/amule-dlp:official-2.3.3
