name: Docker Image CI

on:
  push:
    
jobs:
  build:
    strategy:
      matrix:
        amule_version: [latest, official-2.3.3]

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v2
    
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
          
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
          context: ./
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x,linux/riscv64
          file: ./${{ matrix.amule_version }}/Dockerfile
          push: true
          tags: minnyres/amule-dlp:${{ matrix.amule_version }}
          provenance: false
          sbom: false
